# Generated by Django 4.1.3 on 2022-12-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloggingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPost1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('Write_Post', models.TextField()),
            ],
        ),
    ]
