# Generated by Django 4.1.3 on 2022-12-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloggingApp', '0003_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='add_post',
        ),
        migrations.DeleteModel(
            name='AddPost',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
