# Generated by Django 4.1.3 on 2022-12-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloggingApp', '0004_remove_posts_add_post_delete_addpost_delete_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
