# Generated by Django 4.1.3 on 2022-12-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloggingApp', '0006_delete_image_addpost1_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpost1',
            old_name='image',
            new_name='header_image',
        ),
    ]
